add_rules("mode.debug", "mode.release")
add_requires("spdlog          1.12.0")
add_requires("argparse        2.9")
add_requires("elfio           3.11")
add_requires("nlohmann_json   3.11.2")

target("VTable-Exporter")
    set_kind("binary")
    add_files("src/*.cpp")
    add_includedirs("include")
    add_packages("spdlog")
    add_packages("argparse")
    add_packages("nlohmann_json")
    add_packages("elfio")
    set_symbols("debug")
    set_warnings("all")
    set_optimize("fastest")
    set_languages("cxx20", "c99")
    set_exceptions("cxx")
